### PR TITLE
Added luamqtt client library

### PR DESCRIPTION
**Pull request by xHasKx**

### CODE REVIEW

**Comment by hobbyquaker** [comment]
could you pls modify your PR and stick to alphabetic order?

**Comment by xHasKx** [comment]
Hello,

The [Moscapsule] is not placed in alphabetic order. It was placed like this before my PR.
I can fix its position too. Should I?

**Comment by hobbyquaker** [comment]
oh - yes pls :)

**Comment by xHasKx** [comment]
I propose to sort all positions in all categories, it's easy with "sort lines" command in modern text editors like VS Code or Sublime, but it will led to large diff.
How do you look on this?

**Comment by xHasKx** [comment]
> I propose to sort all positions in all categories, it's easy with "sort lines" command in modern text editors like VS Code or Sublime, but it will led to large diff.
> How do you look on this?

Just because sorting is broken in almost all sections

**Comment by hobbyquaker** [comment]
hmm, as it „should“ be sorted in the categories I would appreciate that ;)

**Pull request merged**
